const crypto = require("crypto");
const { onCall, HttpsError } = require("firebase-functions/v2/https");
const { onInit } = require("firebase-functions/v2/core");
const { setGlobalOptions } = require("firebase-functions/v2/options");
const { logger } = require("firebase-functions");
const { initializeApp } = require("firebase-admin/app");
const { getAuth } = require("firebase-admin/auth");
const { getFirestore, FieldValue } = require("firebase-admin/firestore");

initializeApp();
setGlobalOptions({
  region: "europe-west1",
  maxInstances: 10
});

const db = getFirestore();
const adminAuth = getAuth();

const USERNAME_RE = /^[a-zA-Z0-9._-]{3,32}$/;
const PASSWORD_MIN = 8;
const MAX_TAGS = 20;

// Erstellt nur Dokumente mit Setup-/Schema-Informationen. Die echten Accounts
// werden weiterhin ausschließlich durch bootstrapTobiAdmin/createTobiAccount erzeugt.
async function ensureTobiSetupDocuments() {
  const schemaRef = db.doc("system/schema");
  const maintenanceRef = db.doc("siteSettings/jdnext");

  await db.runTransaction(async transaction => {
    const schemaSnap = await transaction.get(schemaRef);
    const maintenanceSnap = await transaction.get(maintenanceRef);

    if (!schemaSnap.exists) {
      transaction.set(schemaRef, {
        version: 1,
        purpose: "TobiServices Firestore schema reference",
        createdAt: FieldValue.serverTimestamp(),
        collections: {
          tobiAccounts: {
            documentPath: "tobiAccounts/{usernameKey}",
            manualEntryAllowed: false,
            fields: {
              username: "string",
              usernameKey: "string (lowercase username)",
              displayName: "string",
              uid: "string (matching Firebase Authentication UID)",
              tags: "array<string>",
              disabled: "boolean",
              salt: "base64 string; generated by backend",
              passwordHash: "base64 string; scrypt hash generated by backend",
              passwordVersion: "number",
              kdf: "string",
              createdAt: "timestamp",
              updatedAt: "timestamp",
              createdBy: "string; optional"
            }
          },
          users: {
            documentPath: "users/{uid}",
            manualEntryAllowed: false,
            fields: {
              username: "string",
              displayName: "string",
              tags: "array<string>",
              createdAt: "timestamp",
              lastProfileChangeAt: "timestamp"
            }
          }
        },
        secrets: {
          bootstrapKey: {
            name: "TOBI_BOOTSTRAP_KEY",
            storage: "Firebase/Google Cloud Secret Manager",
            storedInFirestore: false
          }
        }
      });
    }

    if (!maintenanceSnap.exists) {
      transaction.set(maintenanceRef, {
        enabled: false,
        message: "",
        updatedAt: FieldValue.serverTimestamp()
      });
    }
  });
}

// Schema-Hinweise und öffentliche Wartungseinstellung beim ersten echten
// Cloud-Functions-Start anlegen, nicht während des Deployments.
onInit(async () => {
  await ensureTobiSetupDocuments();
});

function cleanUsername(value) {
  return String(value ?? "").trim();
}

function usernameKey(value) {
  return cleanUsername(value).toLowerCase();
}

function cleanDisplayName(value) {
  return String(value ?? "").trim().slice(0, 40);
}

function normalizeTags(tags) {
  return [...new Set(
    (Array.isArray(tags) ? tags : [])
      .map(tag => String(tag).toLowerCase().trim())
      .filter(Boolean)
      .map(tag => tag.replace(/[^a-z0-9äöüß_-]+/g, "-").slice(0, 24))
      .filter(Boolean)
  )].slice(0, MAX_TAGS);
}

function assertValidCredentials(username, password) {
  if (!USERNAME_RE.test(username)) {
    throw new HttpsError(
      "invalid-argument",
      "Der Username muss 3–32 Zeichen lang sein und darf nur Buchstaben, Zahlen, Punkt, Unterstrich und Bindestrich enthalten."
    );
  }

  if (typeof password !== "string" || password.length < PASSWORD_MIN || password.length > 128) {
    throw new HttpsError(
      "invalid-argument",
      "Das Passwort muss 8–128 Zeichen lang sein."
    );
  }
}

function makeUid(key) {
  return "tobi_" + crypto
    .createHash("sha256")
    .update("tobiservices:" + key)
    .digest("hex")
    .slice(0, 40);
}

function createPasswordRecord(password) {
  const salt = crypto.randomBytes(16);
  const hash = crypto.scryptSync(password, salt, 64, {
    N: 32768,
    r: 8,
    p: 1,
    maxmem: 64 * 1024 * 1024
  });

  return {
    salt: salt.toString("base64"),
    passwordHash: hash.toString("base64"),
    passwordVersion: 1,
    kdf: "scrypt-N32768-r8-p1"
  };
}

function verifyPassword(password, record) {
  try {
    if (!record?.salt || !record?.passwordHash) return false;

    const salt = Buffer.from(record.salt, "base64");
    const expected = Buffer.from(record.passwordHash, "base64");
    const actual = crypto.scryptSync(password, salt, expected.length, {
      N: 32768,
      r: 8,
      p: 1,
      maxmem: 64 * 1024 * 1024
    });

    return expected.length === actual.length && crypto.timingSafeEqual(expected, actual);
  } catch {
    return false;
  }
}

async function isAdminUid(uid) {
  const snap = await db.doc("users/" + uid).get();
  if (!snap.exists) return false;
  const tags = Array.isArray(snap.data().tags) ? snap.data().tags : [];
  return tags.includes("admin");
}

async function requireAdmin(request) {
  if (!request.auth?.uid) {
    throw new HttpsError("unauthenticated", "Anmeldung erforderlich.");
  }

  if (!(await isAdminUid(request.auth.uid))) {
    throw new HttpsError("permission-denied", "Admin-Rechte erforderlich.");
  }

  return request.auth.uid;
}

async function buildProfile(uid) {
  const snap = await db.doc("users/" + uid).get();
  if (!snap.exists) return null;
  return { uid, ...snap.data() };
}

async function mintToken(account, uid) {
  // The users/{uid} profile is the authoritative source for all role tags.
  const profileSnap = await db.doc("users/" + uid).get();
  const profile = profileSnap.exists ? (profileSnap.data() || {}) : {};
  const tags = normalizeTags(Array.isArray(profile.tags) ? profile.tags : account.tags);
  return adminAuth.createCustomToken(uid, {
    tobi: true,
    admin: tags.includes("admin"),
    tags
  });
}


/**
 * Ensure an authenticated Firebase email/password user has a tag profile.
 * Newly imported/directly-created Firebase Auth users start with no tags.
 * A user can never choose their own tags through this function.
 */
exports.ensureUserProfile = onCall(async (request) => {
  const uid = request.auth?.uid;
  if (!uid) {
    throw new HttpsError("unauthenticated", "Anmeldung erforderlich.");
  }

  const authUser = await adminAuth.getUser(uid);
  const profileRef = db.doc("users/" + uid);
  const profileSnap = await profileRef.get();

  if (!profileSnap.exists) {
    await profileRef.create({
      email: authUser.email || "",
      displayName: authUser.displayName || "",
      tags: [],
      createdAt: FieldValue.serverTimestamp(),
      lastProfileChangeAt: FieldValue.serverTimestamp(),
      authProvider: "firebase-auth"
    }).catch(async error => {
      // A concurrent login may have created the profile after our read.
      if (String(error.code) !== "6" && String(error.code) !== "already-exists") throw error;
    });
  } else {
    const existing = profileSnap.data() || {};
    const patch = {};
    if (typeof existing.email !== "string" && authUser.email) patch.email = authUser.email;
    if (typeof existing.displayName !== "string" && authUser.displayName) patch.displayName = authUser.displayName;
    if (!Array.isArray(existing.tags)) patch.tags = [];
    if (Object.keys(patch).length) {
      await profileRef.set(patch, { merge: true });
    }
  }

  const finalSnap = await profileRef.get();
  return { profile: { uid, ...(finalSnap.data() || {}) } };
});

exports.loginTobiAccount = onCall(async (request) => {
  const username = cleanUsername(request.data?.username);
  const password = request.data?.password;

  if (!USERNAME_RE.test(username) || typeof password !== "string") {
    throw new HttpsError("unauthenticated", "Username oder Passwort ist falsch.");
  }

  const key = usernameKey(username);
  const ref = db.doc("tobiAccounts/" + key);
  const snap = await ref.get();

  if (!snap.exists) {
    throw new HttpsError("unauthenticated", "Username oder Passwort ist falsch.");
  }

  const account = snap.data();

  if (account.disabled === true || !verifyPassword(password, account)) {
    throw new HttpsError("unauthenticated", "Username oder Passwort ist falsch.");
  }

  const token = await mintToken(account, account.uid);
  const profile = await buildProfile(account.uid);

  return {
    token,
    profile: profile || {
      uid: account.uid,
      username: account.username,
      displayName: account.displayName || account.username,
      tags: normalizeTags(account.tags)
    }
  };
});

// The old secret-key bootstrap endpoint was removed. To initialize the first
// admin, an owner sets users/{uid}.tags = ["admin"] for a known Firebase Auth UID
// directly in the trusted Firebase Console. All later changes go through setTobiTags.

exports.createTobiAccount = onCall(async (request) => {
  const adminUid = await requireAdmin(request);

  const username = cleanUsername(request.data?.username);
  const password = request.data?.password;
  const displayName = cleanDisplayName(request.data?.displayName) || username;

  assertValidCredentials(username, password);

  const key = usernameKey(username);
  const ref = db.doc("tobiAccounts/" + key);

  if ((await ref.get()).exists) {
    throw new HttpsError("already-exists", "Dieser Username ist bereits vergeben.");
  }

  await ensureTobiSetupDocuments();

  const uid = makeUid(key);
  const passwordRecord = createPasswordRecord(password);

  await adminAuth.createUser({
    uid,
    displayName
  });

  await ref.set({
    username,
    usernameKey: key,
    displayName,
    uid,
    tags: [],
    disabled: false,
    ...passwordRecord,
    createdAt: FieldValue.serverTimestamp(),
    updatedAt: FieldValue.serverTimestamp(),
    createdBy: adminUid
  });

  await db.doc("users/" + uid).set({
    username,
    displayName,
    tags: [],
    createdAt: FieldValue.serverTimestamp(),
    lastProfileChangeAt: FieldValue.serverTimestamp()
  });

  return {
    ok: true,
    uid,
    username,
    displayName
  };
});

exports.listTobiUsers = onCall(async (request) => {
  await requireAdmin(request);

  const authUsers = [];
  let pageToken;
  do {
    const page = await adminAuth.listUsers(1000, pageToken);
    authUsers.push(...page.users);
    pageToken = page.pageToken;
  } while (pageToken && authUsers.length < 5000);

  const users = await Promise.all(authUsers.map(async user => {
    const profileSnap = await db.doc("users/" + user.uid).get();
    const profile = profileSnap.exists ? (profileSnap.data() || {}) : {};
    return {
      uid: user.uid,
      email: user.email || profile.email || "",
      username: profile.username || user.email || "",
      displayName: profile.displayName || user.displayName || user.email || "",
      tags: Array.isArray(profile.tags) ? profile.tags : [],
      disabled: Boolean(user.disabled || profile.disabled),
      createdAt: profile.createdAt || user.metadata.creationTime || null,
      authProvider: profile.authProvider || (accountSnap.empty ? "firebase-auth" : "tobi-legacy")
    };
  }));

  users.sort((a, b) => String(a.email || a.username).localeCompare(String(b.email || b.username)));
  return { users, truncated: Boolean(pageToken) };
});

exports.setTobiTags = onCall(async (request) => {
  const adminUid = await requireAdmin(request);
  const uid = String(request.data?.uid ?? "");
  const tags = normalizeTags(request.data?.tags);

  if (!uid) {
    throw new HttpsError("invalid-argument", "UID fehlt.");
  }

  if (uid === adminUid && !tags.includes("admin")) {
    throw new HttpsError("failed-precondition", "Du kannst deinen eigenen Admin-Tag nicht entfernen.");
  }

  let authUser;
  try {
    authUser = await adminAuth.getUser(uid);
  } catch {
    throw new HttpsError("not-found", "Firebase-Auth-Account nicht gefunden.");
  }

  const profileRef = db.doc("users/" + uid);
  const profileSnap = await profileRef.get();
  const profile = profileSnap.exists ? (profileSnap.data() || {}) : {};

  const accountSnap = await db.collection("tobiAccounts").where("uid", "==", uid).limit(1).get();
  const batch = db.batch();
  batch.set(profileRef, {
    email: authUser.email || profile.email || "",
    username: profile.username || authUser.email || "",
    displayName: profile.displayName || authUser.displayName || authUser.email || "",
    tags,
    lastProfileChangeAt: FieldValue.serverTimestamp(),
    authProvider: profile.authProvider || "firebase-auth"
  }, { merge: true });

  if (!profileSnap.exists) {
    batch.set(profileRef, { createdAt: FieldValue.serverTimestamp() }, { merge: true });
  }

  if (!accountSnap.empty) {
    batch.update(accountSnap.docs[0].ref, {
      tags,
      updatedAt: FieldValue.serverTimestamp(),
      updatedBy: adminUid
    });
  }

  await batch.commit();
  return { ok: true, uid, tags };
});

exports.setMaintenanceMode = onCall(async (request) => {
  const adminUid = await requireAdmin(request);

  const enabled = request.data?.enabled === true;
  const message = String(request.data?.message ?? "").trim().slice(0, 500);

  await db.doc("siteSettings/jdnext").set({
    enabled,
    message,
    updatedAt: FieldValue.serverTimestamp()
  }, { merge: true });

  logger.info("JDNEXT maintenance mode changed", {
    enabled,
    updatedBy: adminUid
  });

  return { ok: true, enabled, message };
});

exports.setTobiDisabled = onCall(async (request) => {
  const adminUid = await requireAdmin(request);
  const uid = String(request.data?.uid ?? "");
  const disabled = Boolean(request.data?.disabled);

  if (!uid) {
    throw new HttpsError("invalid-argument", "UID fehlt.");
  }
  if (uid === adminUid && disabled) {
    throw new HttpsError("failed-precondition", "Du kannst deinen eigenen Account hier nicht deaktivieren.");
  }

  let authUser;
  try {
    authUser = await adminAuth.getUser(uid);
  } catch {
    throw new HttpsError("not-found", "Firebase-Auth-Account nicht gefunden.");
  }

  const accountSnap = await db.collection("tobiAccounts").where("uid", "==", uid).limit(1).get();
  await adminAuth.updateUser(uid, { disabled });
  await db.doc("users/" + uid).set({
    email: authUser.email || "",
    displayName: authUser.displayName || authUser.email || "",
    disabled,
    lastProfileChangeAt: FieldValue.serverTimestamp(),
    authProvider: accountSnap.empty ? "firebase-auth" : "tobi-legacy"
  }, { merge: true });

  if (!accountSnap.empty) {
    await accountSnap.docs[0].ref.update({
      disabled,
      updatedAt: FieldValue.serverTimestamp(),
      updatedBy: adminUid
    });
  }

  return { ok: true, uid, disabled, email: authUser.email || "" };
});
